/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  8453: {
    CLAWDdcaV3: {
      address: "0x096f3db3c7910061d798a2e2865844a24d13bf9c",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "initialOwner",
              type: "address",
              internalType: "address",
            },
            {
              name: "initialBurnSwapPath",
              type: "bytes",
              internalType: "bytes",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "BPS_DENOMINATOR",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "BURN_ADDRESS",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "BURN_FEE_BPS",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "CLAWD",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "DEFAULT_SLIPPAGE_BPS",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "EPOCH_DURATION",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "KEEPER_FEE_BPS",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "MAX_SLIPPAGE_BPS",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "MIN_AMOUNT_PER_SWAP",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "PROTOCOL_FEE_BPS",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "QUOTER",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "SWAP_ROUTER",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "USDC",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "WETH",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "acceptOwnership",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "burnFeeBalance",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "burnSwapPath",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "bytes",
              internalType: "bytes",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "closePosition",
          inputs: [
            {
              name: "positionId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "createPosition",
          inputs: [
            {
              name: "totalUSDC",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "amountPerSwap",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "intervalInEpochs",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "targetToken",
              type: "address",
              internalType: "address",
            },
            {
              name: "swapPath",
              type: "bytes",
              internalType: "bytes",
            },
            {
              name: "slippageBps",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "positionId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "createPositionViaWETH",
          inputs: [
            {
              name: "totalUSDC",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "amountPerSwap",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "intervalInEpochs",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "targetToken",
              type: "address",
              internalType: "address",
            },
            {
              name: "usdcWethFee",
              type: "uint24",
              internalType: "uint24",
            },
            {
              name: "wethTargetFee",
              type: "uint24",
              internalType: "uint24",
            },
            {
              name: "slippageBps",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "positionId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "currentEpoch",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "executeBatch",
          inputs: [
            {
              name: "positionIds",
              type: "uint256[]",
              internalType: "uint256[]",
            },
          ],
          outputs: [
            {
              name: "results",
              type: "uint256[]",
              internalType: "uint256[]",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "executeBurn",
          inputs: [],
          outputs: [
            {
              name: "clawdBurned",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "executeDCA",
          inputs: [
            {
              name: "positionId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "tokenReceived",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "executeDCAFromBatch",
          inputs: [
            {
              name: "positionId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "tokenReceived",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "executeDCAWithMin",
          inputs: [
            {
              name: "positionId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "amountOutMinimum",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "tokenReceived",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "getPosition",
          inputs: [
            {
              name: "positionId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "tuple",
              internalType: "struct CLAWDdcaV3.Position",
              components: [
                {
                  name: "owner",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "targetToken",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "swapPath",
                  type: "bytes",
                  internalType: "bytes",
                },
                {
                  name: "usdcBalance",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "tokenAccrued",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "amountPerSwap",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "intervalInEpochs",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "lastExecutedEpoch",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "slippageBps",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "active",
                  type: "bool",
                  internalType: "bool",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getPositionsByOwner",
          inputs: [
            {
              name: "user",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256[]",
              internalType: "uint256[]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getRipePositions",
          inputs: [
            {
              name: "positionIds",
              type: "uint256[]",
              internalType: "uint256[]",
            },
          ],
          outputs: [
            {
              name: "ripe",
              type: "uint256[]",
              internalType: "uint256[]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "isRipe",
          inputs: [
            {
              name: "positionId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "nextPositionId",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "owner",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "pause",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "paused",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "pendingOwner",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "positions",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
            {
              name: "targetToken",
              type: "address",
              internalType: "address",
            },
            {
              name: "swapPath",
              type: "bytes",
              internalType: "bytes",
            },
            {
              name: "usdcBalance",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "tokenAccrued",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "amountPerSwap",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "intervalInEpochs",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "lastExecutedEpoch",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "slippageBps",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "active",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "positionsByOwner",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "protocolFeeBalance",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "renounceOwnership",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setBurnSwapPath",
          inputs: [
            {
              name: "newPath",
              type: "bytes",
              internalType: "bytes",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "transferOwnership",
          inputs: [
            {
              name: "newOwner",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "unpause",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "withdrawProtocolFees",
          inputs: [
            {
              name: "to",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "withdrawToken",
          inputs: [
            {
              name: "positionId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "BurnExecuted",
          inputs: [
            {
              name: "executor",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "usdcIn",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "clawdBurned",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "BurnSwapPathUpdated",
          inputs: [
            {
              name: "newPath",
              type: "bytes",
              indexed: false,
              internalType: "bytes",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "OwnershipTransferStarted",
          inputs: [
            {
              name: "previousOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "newOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "OwnershipTransferred",
          inputs: [
            {
              name: "previousOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "newOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Paused",
          inputs: [
            {
              name: "account",
              type: "address",
              indexed: false,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "PositionClosed",
          inputs: [
            {
              name: "positionId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "closedBy",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "usdcRefunded",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "tokenRefunded",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "PositionCreated",
          inputs: [
            {
              name: "positionId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "owner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "targetToken",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "totalUSDC",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "amountPerSwap",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "intervalInEpochs",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "slippageBps",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "PositionExecuted",
          inputs: [
            {
              name: "positionId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "keeper",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amountSwapped",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "tokenReceived",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "keeperFee",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "epoch",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "ProtocolFeesWithdrawn",
          inputs: [
            {
              name: "to",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "TokenWithdrawn",
          inputs: [
            {
              name: "positionId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "owner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Unpaused",
          inputs: [
            {
              name: "account",
              type: "address",
              indexed: false,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "BurnPathNotSet",
          inputs: [],
        },
        {
          type: "error",
          name: "EmptyBatch",
          inputs: [],
        },
        {
          type: "error",
          name: "EnforcedPause",
          inputs: [],
        },
        {
          type: "error",
          name: "ExpectedPause",
          inputs: [],
        },
        {
          type: "error",
          name: "InsufficientBalance",
          inputs: [],
        },
        {
          type: "error",
          name: "InvalidAmount",
          inputs: [],
        },
        {
          type: "error",
          name: "InvalidInterval",
          inputs: [],
        },
        {
          type: "error",
          name: "InvalidPath",
          inputs: [],
        },
        {
          type: "error",
          name: "InvalidSlippage",
          inputs: [],
        },
        {
          type: "error",
          name: "NotOwnerOrPositionOwner",
          inputs: [],
        },
        {
          type: "error",
          name: "NotPositionOwner",
          inputs: [],
        },
        {
          type: "error",
          name: "NothingToBurn",
          inputs: [],
        },
        {
          type: "error",
          name: "NothingToWithdraw",
          inputs: [],
        },
        {
          type: "error",
          name: "OwnableInvalidOwner",
          inputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "OwnableUnauthorizedAccount",
          inputs: [
            {
              name: "account",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "PathTokenMismatch",
          inputs: [],
        },
        {
          type: "error",
          name: "PositionInactive",
          inputs: [],
        },
        {
          type: "error",
          name: "PositionNotRipe",
          inputs: [],
        },
        {
          type: "error",
          name: "ReentrancyGuardReentrantCall",
          inputs: [],
        },
        {
          type: "error",
          name: "SafeERC20FailedOperation",
          inputs: [
            {
              name: "token",
              type: "address",
              internalType: "address",
            },
          ],
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 46298902,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
